# Site Settings
baseurl: ""
url : "https://hwuiwon.github.io"

# Blog Settings
theme_settings :
  title : Huey Kim
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Huey Kim
    description : IE student at Georgia Tech with the focus of Supply Chain Engineering
    experience :
      - start : 2019-05-08
        end : 2019-07-26
        experience : Koreana Patent Law Firm, Intern
      - start : 2018-10-26
        end : 2018-10-28
        experience : HackATL, Participant
      - start : 2018-01-01
        end : 2018-06-01
        experience : SK Broadband, Part-time
    skills : 
      - skill : Java
        value : 85  # Percent value
      - skill : Android Programming
        value : 70  # Percent value
      - skill : MySQL
        value : 60  # Percent value
        
  # Icons
  icons :
    email: hwuiwon.kim@gmail.com
    linkedin: https://www.linkedin.com/in/hueyk/
    github: hwuiwon
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
